[package]
name = "valu3"
version = "0.9.2"
edition = "2021"
license = "Apache-2.0"
readme = "crates-io.md"
authors = ["Philippe Assis <codephilippe@gmail.com>"]
repository = "https://github.com/lowcarboncode/valu3"
keywords = ["value", "generic", "type", "serde", "parsing"]
description = "A generic serialization/deserialization/type framework"
categories = ["encoding", "no-std", "parsing"]
documentation = "https://docs.rs/valu3"

[dependencies]
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.11.1"
chrono = "0.4.39"
serde = { version = "1.0.216", features = ["derive"], optional = true }
valu3-derive = { path = "../valu3_derive", optional = true, version = "0.9.2" }

[dev-dependencies]
rand = "0.9.2"
serde_json = "1.0.134"

[features]
default = ["parser", "derive", "serde"]
parser = ["json"]
json = []
serde = ["dep:serde"]
cstring = []
derive = ["dep:valu3-derive"]

[lib]
doctest = false
